name: upload-artifact
on:
  push:
    branches: [main]
jobs:
  Create-directory:
    runs-on: ubuntu-latest
    steps:
      - name: create directory
        run: mkdir -p build
  create-content:
    runs-on: ubuntu-latest
    needs: Create-directory
    id: create-content
    steps:
      - name: create content
        run: echo 'hiiiii' > build/hello.txt
  create-artifact:
    runs-on: ubuntu-latest
    depends_on: steps.create-content.outcome = 'success'
    steps:
      - name: create artifact
        run: zip -r build.zip build
  upload-artifact:
    runs-on: ubuntu-latest
    needs: create-artifact
    steps:
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: build-artifact
            path: build.zip