name: upload-artifact
on:
  push:
    branches: feature/**
jobs:
  create-directory:
    runs-on: ubuntu-latest
    steps:
      - name: create directory
        run: mkdir -p build
      - name: create content
        run: echo 'hiiiii' > build/hello.txt
      - name: create artifact
        run: zip -r build.zip build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: build-artifact
            path: build.zip