name: Greeting Bot
on:
  issues:
    types:
      [opened]
  issue_comment:
    types:
      [created]
permissions:
  issues: write      
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: greet bot
      uses: peter-evans/create-or-update-comment@v4   
      with:
        token: ${{ secrets.GITHUB_TOKEN }}   
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hi @${{ github.event.issue.user.login }}! :wave: Thanks for opening this issue! We will look into it as soon as possible.