name : CI
on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - feature/**
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: runs-on ${{ matrix.os }}
        run: echo $RUNNER_OS
      - name: username
        run: echo $USER