name: Bot
on:
  issues:
    types:
      - opened
      - edited
      - reopened
      - closed
  issue_comment:
    types:
      - created
permissions:
  issues: write
jobs:
  Issue:
    if: github.event_name == "issue"
    runs-on: ubuntu-latest
    steps:
      - name: greet bot
        if: ${{ github.event_name == 'issue' && github.event.action == 'opened' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.event.issue.user.login }}! :wave: Thanks for opening this issue! We will look into it as soon as possible.
      - name: edit comment
        if: github.event.action == "edited"
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
              Hi @${{ github.event.issue.user.login }}! :wave: Thanks for editing this issue! We will look into it as soon as possible.
      - name: reopen comment
        if: github.event.action == "reopened"
        uses: peter-evans/create-or-update-comment@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            issue-number: ${{ github.event.issue.number }}
            body: |
              Hi @${{ github.event.issue.user.login }}! :wave: Thanks for reopening this issue! We will look into it as soon as possible.
      - name: close comment
        if: github.event.action == "closed"
        uses: peter-evans/create-or-update-comment@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            issue-number: ${{ github.event.issue.number }}
            body: |
              Hi @${{ github.event.issue.user.login }}! :wave: Thanks for closing this issue! We will look into it as soon as possible.
  comment:
      if: github.event_name == "issue_comment"
      runs-on: ubuntu-latest
      steps:
        - name: comment on issue
          uses: peter-evans/create-or-update-comment@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            issue-number: ${{ github.event.issue.number }}
            body: |
              Hi @${{ github.event.issue.user.login }}! :wave: Thanks for your comment! We will look into it as soon as possible.