name: "Workflow2"
run-name: "${{ github.actor }} workflow running"
on:
  push:
    branches:
      - feature/**
permissions:
  contents: read
jobs:
  Test-run:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo hello
      - name: github branch
        run: echo ${{ github.ref }}
      - name: github repo
        run: echo ${{ github.repository }}
      - name: github workspace
        run: echo ${{ github.workspace}}
      - name: github event name
        run: echo ${{ github.event_name }}
